-- DROP TABLE PERSONA
CREATE TABLE PERSONA (
    PERSONA_ID SERIAL NOT NULL,
    NOMBRE CHARACTER VARYING(90) NOT NULL,
    GENERO CHARACTER VARYING(2) NOT NULL,
    EDAD SMALLINT NOT NULL,
    IDENTIFICACION CHARACTER VARYING(10) NOT NULL,
    DIRECCION CHARACTER VARYING(90) NOT NULL,
    TELEFONO CHARACTER VARYING(10) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);

-- CREATE PK FOR TABLE PERSONA
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_PK PRIMARY KEY (PERSONA_ID);

-- DROP TABLE CLIENTE
CREATE TABLE CLIENTE (
    CLIENTE_ID SERIAL NOT NULL,
    PERSONA_ID INTEGER NOT NULL,
    CONTRASENA CHARACTER VARYING(30) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);

-- CREATE PK FOR TABLE CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID);

-- CREATE FK FOR TABLE CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_FK FOREIGN KEY (PERSONA_ID) 
    REFERENCES PERSONA (PERSONA_ID);

-- DROP TABLE CUENTA
CREATE TABLE CUENTA (
    CUENTA_ID SERIAL NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    NUMERO_CUENTA CHARACTER VARYING(30) NOT NULL,
    TIPO_CUENTA CHARACTER VARYING(30) NOT NULL,
    SALDO_INICIAL NUMERIC(19,2) NOT NULL,
    SALDO_ACTUAL NUMERIC(19,2) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE PK FOR TABLE CUENTA
ALTER TABLE CUENTA ADD CONSTRAINT CUENTA_PK PRIMARY KEY (CUENTA_ID);

-- CREATE FK FOR TABLE CUENTA
ALTER TABLE CUENTA ADD CONSTRAINT CUENTA_FK FOREIGN KEY (CLIENTE_ID) 
    REFERENCES CLIENTE (CLIENTE_ID);

CREATE TABLE MOVIMIENTO (
    MOVIMIENTO_ID SERIAL NOT NULL,
    CUENTA_ID INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    TIPO_MOVIMIENTO CHARACTER VARYING(30) NOT NULL,
    VALOR NUMERIC(19,2) NOT NULL,
    SALDO NUMERIC(19,2) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);

-- CREATE PK FOR TABLE MOVIMIENTO
ALTER TABLE MOVIMIENTO ADD CONSTRAINT MOVIMIENTO_PK PRIMARY KEY (MOVIMIENTO_ID);