-- DROP TABLE CUENTA
CREATE TABLE CUENTA (
    CUEN_ID SERIAL NOT NULL,
    NUMERO_CUENTA CHARACTER VARYING(30) NOT NULL,
    TIPO_CUENTA CHARACTER VARYING(30) NOT NULL,
    SALDO_INICIAL NUMERIC(19,2) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE PK FOR TABLE AEROPUERTO
ALTER TABLE CUENTA ADD CONSTRAINT CUENTA_PK PRIMARY KEY (CUEN_ID);

